export const SITE_CONFIG = {
  name: 'Arian Saeed Industrial Group Inc.',
  description: 'A value-driven company established in 1982, operating 32 companies across wood-based panels, petrochemicals, trade, AI, construction, investment, and many other industries.',
  url: 'https://www.ariansaeed.com',
  ogImage: 'https://www.ariansaeed.com/og-image.jpg',
  links: {
    linkedin: 'https://linkedin.com',
    instagram: 'https://instagram.com',
    twitter: 'https://twitter.com',
  },
}

export const BUSINESS_DOMAINS = [
  {
    id: 'wood-panels',
    title: 'Wood-Based Panels',
    description: 'Production of world-class MDF and wood fiber compressed products with Western European technology, especially from Germany.',
    icon: 'Box',
    gradient: 'from-amber-500 to-orange-500',
    image: '/images/1.jpg',
  },
  {
    id: 'petrochemicals',
    title: 'Petrochemicals',
    description: 'Two chemical factories supporting production with advanced chemical solutions and equipment.',
    icon: 'Droplet',
    gradient: 'from-purple-500 to-pink-500',
    image: '/images/2.jpg',
  },
  {
    id: 'ai-tech',
    title: 'AI & Technology',
    description: 'Data analytics, computer vision, and smart automation to improve decisions and accelerate operations.',
    icon: 'Brain',
    gradient: 'from-indigo-500 to-purple-500',
    image: '/images/1_bigstock-Ai-Car-Fix-Technology-Ai-Fix-471835423.jpg',
  },
  {
    id: 'renewable-energy',
    title: 'Renewable Energy',
    description: 'Solar, wind, and hydroelectric power solutions with cutting-edge photovoltaic technology and sustainable energy management systems.',
    icon: 'Sun',
    gradient: 'from-yellow-500 to-orange-500',
    image: '/images/solarpark-limbach-dorf-Xpert.Digital-png.png',
  },
  {
    id: 'investment',
    title: 'Investment & Finance',
    description: 'Portfolio management and project financing focused on sustainable returns and long‑term growth.',
    icon: 'TrendingUp',
    gradient: 'from-amber-500 to-yellow-500',
    image: '/images/IMG_Mst_Invest_Wealth_Manage.jpg',
  },
  {
    id: 'green-vehicles',
    title: 'Green Vehicles',
    description: 'Sales network and after‑sales services for BYD electric vehicles, delivering clean and efficient mobility solutions.',
    icon: 'Car',
    gradient: 'from-green-500 to-emerald-500',
    image: '/images/1053127.jpg',
  },
]

export const COMPANY_STATS = [
  { label: 'Years of Excellence', value: '42+', icon: 'Calendar' },
  { label: 'Active Companies', value: '32', icon: 'Briefcase' },
  { label: 'Employees', value: '1,500+', icon: 'Users' },
  { label: 'Production Lines', value: '12', icon: 'Factory' },
]

export const SUBSIDIARY_COMPANIES = [
  {
    id: 1,
    name: 'Abshineh',
    logo: '/logo/abshineh.png',
    description: 'Industry leader in manufacturing excellence',
    website: '#',
  },
  {
    id: 2,
    name: 'Arashpooya',
    logo: '/logo/arashpooya.png',
    description: 'Innovative solutions provider',
    website: '#',
  },
  {
    id: 3,
    name: 'Arian Afarin',
    logo: '/logo/arianafarin.png',
    description: 'Premium quality production',
    website: '#',
  },
  {
    id: 4,
    name: 'Arian Arkin',
    logo: '/logo/arianarkin.png',
    description: 'Advanced manufacturing solutions',
    website: '#',
  },
  {
    id: 5,
    name: 'Arian Atie Hsaeed',
    logo: '/logo/arianatiehsaeed.png',
    description: 'Excellence in industrial services',
    website: '#',
  },
  {
    id: 6,
    name: 'Arian Board',
    logo: '/logo/arianboard.png',
    description: 'Premium board manufacturing',
    website: '#',
  },
  {
    id: 7,
    name: 'Arian Dadeh',
    logo: '/logo/ariandadeh.png',
    description: 'Innovative industrial solutions',
    website: '#',
  },
  {
    id: 8,
    name: 'Arian Jalarang',
    logo: '/logo/arianjalarang.png',
    description: 'Leading manufacturing group',
    website: '#',
  },
  {
    id: 9,
    name: 'Arian Leila',
    logo: '/logo/arianleila.png',
    description: 'Quality production services',
    website: '#',
  },
  {
    id: 10,
    name: 'Arian Maryam',
    logo: '/logo/arianmaryam.png',
    description: 'Advanced industrial operations',
    website: '#',
  },
  {
    id: 11,
    name: 'Arian MDF',
    logo: '/logo/arianmdf.png',
    description: 'Premium MDF board production',
    website: '#',
  },
  {
    id: 12,
    name: 'Arian Naron',
    logo: '/logo/ariannaron.png',
    description: 'Specialized manufacturing services',
    website: '#',
  },
  {
    id: 13,
    name: 'Arian Novin',
    logo: '/logo/ariannovin.png',
    description: 'Modern industrial solutions',
    website: '#',
  },
  {
    id: 14,
    name: 'Arian Payesh',
    logo: '/logo/arianpayesh.png',
    description: 'Quality control and monitoring',
    website: '#',
  },
  {
    id: 15,
    name: 'Arian Rahvar',
    logo: '/logo/arianrahvar.png',
    description: 'Industrial excellence provider',
    website: '#',
  },
  {
    id: 16,
    name: 'Arian Rauch',
    logo: '/logo/arianrauch.png',
    description: 'Advanced manufacturing technology',
    website: '#',
  },
  {
    id: 17,
    name: 'Arian Saeed',
    logo: '/logo/ariansaeed.png',
    description: 'Holding company excellence',
    website: '#',
  },
  {
    id: 18,
    name: 'Arian Shadab',
    logo: '/logo/arianshadab.png',
    description: 'Innovation and quality',
    website: '#',
  },
  {
    id: 19,
    name: 'Arian Shimi',
    logo: '/logo/arianshimi.png',
    description: 'Chemical solutions provider',
    website: '#',
  },
  {
    id: 20,
    name: 'Arian Sina',
    logo: '/logo/ariansina.png',
    description: 'Industrial services excellence',
    website: '#',
  },
  {
    id: 21,
    name: 'Arian Takhteh',
    logo: '/logo/ariantakhteh.png',
    description: 'Board production specialist',
    website: '#',
  },
  {
    id: 22,
    name: 'Arian Tamin',
    logo: '/logo/ariantamin.png',
    description: 'Quality assurance services',
    website: '#',
  },
  {
    id: 23,
    name: 'Arian Tarabar',
    logo: '/logo/ariantarabar.png',
    description: 'Logistics and operations',
    website: '#',
  },
  {
    id: 24,
    name: 'Arina Dadeh',
    logo: '/logo/arinadadehh.png',
    description: 'Manufacturing excellence',
    website: '#',
  },
  {
    id: 25,
    name: 'Arina Setad',
    logo: '/logo/arinasetad.png',
    description: 'Strategic operations',
    website: '#',
  },
  {
    id: 26,
    name: 'ASIGI',
    logo: '/logo/asigi.png',
    description: 'Industrial group holding',
    website: '#',
  },
  {
    id: 27,
    name: 'Chasb Saz',
    logo: '/logo/chasbsaz.png',
    description: 'Adhesive production',
    website: '#',
  },
  {
    id: 28,
    name: 'Modir Project',
    logo: '/logo/modirproject.png',
    description: 'Project management services',
    website: '#',
  },
  {
    id: 29,
    name: 'Sina MDF',
    logo: '/logo/sinamdf.png',
    description: 'MDF manufacturing solutions',
    website: '#',
  },
]

export const CONTACT_INFO = {
  address: 'Tehran, Iran',
  phone: '+98 21 1234 5678',
  email: 'info@ariansaeedholding.com',
  mapCenter: {
    lat: 35.77857469321197,
    lng: 51.423923904739006,
  },
}

export const PARTNER_LOCATIONS = [
  { city: 'Tehran', country: 'Iran', lat: 35.77857469321197, lng: 51.423923904739006, isBase: true },
  { city: 'Istanbul', country: 'Turkey', lat: 41.0082, lng: 28.9784 },
  { city: 'Dubai', country: 'UAE', lat: 25.2048, lng: 55.2708 },
  { city: 'Muscat', country: 'Oman', lat: 23.5880, lng: 58.3829 },
  { city: 'Berlin', country: 'Germany', lat: 52.5200, lng: 13.4050 },
  { city: 'Beijing', country: 'China', lat: 39.9042, lng: 116.4074 },
  { city: 'Baku', country: 'Azerbaijan', lat: 40.4093, lng: 49.8671 },
  { city: 'Moscow', country: 'Russia', lat: 55.7558, lng: 37.6173 },
  { city: 'Dushanbe', country: 'Tajikistan', lat: 38.5598, lng: 68.7738 },
  { city: 'Baghdad', country: 'Iraq', lat: 33.3152, lng: 44.3661 },
  { city: 'Damascus', country: 'Syria', lat: 33.5138, lng: 36.2765 },
  { city: 'Beirut', country: 'Lebanon', lat: 33.8886, lng: 35.4955 },
]

export const NAVIGATION_ITEMS = [
  { label: 'Home', href: '/' },
  { label: 'About Us', href: '/about' },
  { label: 'Business Domains', href: '/#domains' },
  { label: 'Articles', href: '/articles' },
  { label: 'Contact', href: '/contact' },
  { label: 'Careers', href: '/careers' },
]
