# Generated by Django 4.2.26 on 2025-11-20 12:47

import apps.careers.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200, verbose_name='Job Title')),
                ('slug', models.SlugField(max_length=250, unique=True, verbose_name='Slug')),
                ('department', models.CharField(db_index=True, max_length=100, verbose_name='Department')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('employment_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full-time', max_length=20, verbose_name='Employment Type')),
                ('description', models.TextField(help_text='Detailed description of the job role', verbose_name='Job Description')),
                ('requirements', models.TextField(blank=True, help_text='Required skills and qualifications', verbose_name='Requirements')),
                ('responsibilities', models.TextField(blank=True, help_text='Key responsibilities of the role', verbose_name='Responsibilities')),
                ('benefits', models.TextField(blank=True, help_text='Benefits and perks', verbose_name='Benefits')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Salary')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximum Salary')),
                ('salary_currency', models.CharField(default='USD', max_length=3, verbose_name='Currency')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('closed', 'Closed')], db_index=True, default='active', max_length=20, verbose_name='Status')),
                ('featured', models.BooleanField(default=False, help_text='Display this job prominently', verbose_name='Featured Job')),
                ('application_deadline', models.DateField(blank=True, null=True, verbose_name='Application Deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Views Count')),
                ('applications_count', models.PositiveIntegerField(default=0, verbose_name='Applications Count')),
            ],
            options={
                'verbose_name': 'Job Listing',
                'verbose_name_plural': 'Job Listings',
                'ordering': ['-featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(db_index=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('position', models.CharField(max_length=200, verbose_name='Desired Position')),
                ('location', models.CharField(max_length=200, verbose_name='Current Location')),
                ('experience', models.CharField(choices=[('0-1', '0-1 years'), ('1-3', '1-3 years'), ('3-5', '3-5 years'), ('5-10', '5-10 years'), ('10+', '10+ years')], max_length=10, verbose_name='Years of Experience')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Cover Letter')),
                ('resume_file', models.FileField(help_text='Allowed formats: PDF, DOC, DOCX', upload_to=apps.careers.models.resume_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])], verbose_name='Resume/CV File')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Under Review'), ('shortlisted', 'Shortlisted'), ('interviewed', 'Interviewed'), ('rejected', 'Rejected'), ('hired', 'Hired')], db_index=True, default='new', max_length=20, verbose_name='Application Status')),
                ('recruiter_notes', models.TextField(blank=True, help_text='Internal notes for HR team', null=True, verbose_name='Recruiter Notes')),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Recruiter rating', null=True, verbose_name='Rating (1-5)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Submitted At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='careers.job', verbose_name='Applied Job')),
            ],
            options={
                'verbose_name': 'Resume/Application',
                'verbose_name_plural': 'Resumes/Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['-created_at', 'status'], name='careers_job_created_0d14d4_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['department', 'status'], name='careers_job_departm_c6617a_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['-created_at', 'status'], name='careers_res_created_70d1ae_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['email', 'status'], name='careers_res_email_f307ea_idx'),
        ),
    ]
