# Generated by Django 4.2.26 on 2025-11-20 12:47

import apps.articles.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first', verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='Title')),
                ('slug', models.SlugField(max_length=350, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(help_text='Short summary of the article', max_length=500, verbose_name='Excerpt')),
                ('content', models.TextField(help_text='Full article content', verbose_name='Content')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500, verbose_name='Tags')),
                ('image', models.ImageField(help_text='Main image for the article', upload_to=apps.articles.models.article_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Featured Image')),
                ('author', models.CharField(default='Editorial Team', max_length=200, verbose_name='Author Name')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20, verbose_name='Status')),
                ('featured', models.BooleanField(default=False, help_text='Display this article prominently', verbose_name='Featured')),
                ('publish_date', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Publish Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='Views Count')),
                ('likes_count', models.PositiveIntegerField(default=0, verbose_name='Likes Count')),
                ('read_time', models.PositiveIntegerField(default=5, help_text='Estimated reading time in minutes', verbose_name='Read Time (minutes)')),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description (max 160 chars)', max_length=160, verbose_name='Meta Description')),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords, comma-separated', max_length=500, verbose_name='Meta Keywords')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Viewed At')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_views', to='articles.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Article View',
                'verbose_name_plural': 'Article Views',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['article', '-created_at'], name='articles_ar_article_4017e1_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='Session Key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Liked At')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_likes', to='articles.article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Article Like',
                'verbose_name_plural': 'Article Likes',
                'indexes': [models.Index(fields=['article', 'ip_address'], name='articles_ar_article_ecc8a4_idx')],
                'unique_together': {('article', 'ip_address')},
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-publish_date', 'status'], name='articles_ar_publish_f2f373_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'status'], name='articles_ar_categor_961ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-views_count'], name='articles_ar_views_c_a0dd47_idx'),
        ),
    ]
